import { ElementRef, EventEmitter, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { PDFDocumentProxy } from 'ng2-pdf-viewer';
import { PdfPreviewZoomScaleType } from '../constants/pdf-preview.constants';
import { UntypedFormGroup } from '@angular/forms';
import { PercentageInputMaskDirective } from '../../../forms/percentage-input-mask.directive';
import { PdfPreviewMagnifyingGlassComponent } from '../pdf-preview-magnifying-glass/pdf-preview-magnifying-glass.component';
import { PdfPreviewCopyToClipboardComponent } from '../pdf-preview-copy-to-clipboard/pdf-preview-copy-to-clipboard.component';
import { PdfPreviewSignPlaceholderComponent } from '../pdf-preview-sign-placeholder/pdf-preview-sign-placeholder.component';
import * as i0 from "@angular/core";
export declare class PdfPreviewComponent implements OnInit, OnChanges {
    element: ElementRef;
    zoomPercentageMask: PercentageInputMaskDirective;
    pdfPreviewMagnifyingGlassComponent: PdfPreviewMagnifyingGlassComponent;
    pdfPreviewCopyToClipboardComponent: PdfPreviewCopyToClipboardComponent;
    pdfPreviewSignPlaceholderComponent: PdfPreviewSignPlaceholderComponent;
    pdfSrc: string | {
        url: string;
        httpHeaders?: unknown;
        withCredentials?: boolean;
    };
    downloadUrl: string;
    fullScreenUrl: string;
    defaultZoom: number;
    fitToPageHeightLabel: string;
    fitToPageWidthLabel: string;
    fitToEntirePageLabel: string;
    downloadButtonLabel: string;
    fullScreenButtonLabel: string;
    pageLabel: string;
    errorMessage: string;
    magnifyingGlassTooltip: string;
    magnifyingGlassEnabledTooltip: string;
    magnifyingGlassEnabled: boolean;
    magnifyingGlassDefaultState: boolean;
    magnifyingGlassMouseSensibility: number;
    magnifyingSize: string | number;
    placeHolderSize: {
        height: number | string;
        width: number | string;
    };
    signPlaceholderMouseSensibility: number;
    enableSignPlaceholder: boolean;
    labelSignaturePlaceholder: string;
    signPlaceholderCoordinates: EventEmitter<any>;
    automaticallyCopySelection: boolean;
    copiedLabel: string;
    automaticallyCopySelectionDelay: number;
    automaticallyCopySelectionTooltipCloseDelay: number;
    disablePdfOptions: boolean;
    pdfLoaded: EventEmitter<PDFDocumentProxy>;
    pdfError: EventEmitter<unknown>;
    magnifyingGlassVisibilityChanged: EventEmitter<boolean>;
    showAllPages: boolean;
    isMagnifyingGlassVisible: boolean;
    isSignPlaceholderVisible: boolean;
    zoomScale: PdfPreviewZoomScaleType;
    page: number;
    zoom: number;
    totalPages: any;
    zoomScaleTypes: {
        readonly PAGE_WIDTH: "page-width";
        readonly PAGE_HEIGHT: "page-height";
        readonly PAGE_FIT: "page-fit";
    };
    isZoomControlDropdownOpen: boolean;
    pdfPreviewHasErrors: boolean;
    form: UntypedFormGroup;
    document: PDFDocumentProxy;
    constructor(element: ElementRef);
    get magnifyingGlassButtonColor(): "var(--up-neutral-500)" | "var(--up-brand-1-700)";
    get prevPageButtonColor(): "var(--up-neutral-500)" | "var(--up-brand-1-700)";
    get nextPageButtonColor(): "var(--up-neutral-500)" | "var(--up-brand-1-700)";
    get zoomOutButtonColor(): "var(--up-neutral-500)" | "var(--up-brand-1-700)";
    get controlColor(): "var(--up-neutral-500)" | "var(--up-brand-1-700)";
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    setCoordinates(event: any): void;
    afterLoadComplete(pdf: PDFDocumentProxy): void;
    activateSignPlaceholder(): void;
    activateMagnifyingGlass(): void;
    deactivateMagnifyingGlass(): void;
    onLoadError(error: unknown): void;
    onZoomControlsDropdownOpen(): void;
    onZoomControlsDropdownClose(): void;
    pageFit(): void;
    pageWidth(): void;
    pageHeight(): void;
    nextPage(): void;
    prevPage(): void;
    zoomIn(): void;
    zoomOut(): void;
    zoomPercentageChanged(): void;
    pageChanged(): void;
    private resetZoom;
    static ɵfac: i0.ɵɵFactoryDeclaration<PdfPreviewComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PdfPreviewComponent, "up-pdf-preview", never, { "pdfSrc": "pdfSrc"; "downloadUrl": "downloadUrl"; "fullScreenUrl": "fullScreenUrl"; "defaultZoom": "defaultZoom"; "fitToPageHeightLabel": "fitToPageHeightLabel"; "fitToPageWidthLabel": "fitToPageWidthLabel"; "fitToEntirePageLabel": "fitToEntirePageLabel"; "downloadButtonLabel": "downloadButtonLabel"; "fullScreenButtonLabel": "fullScreenButtonLabel"; "pageLabel": "pageLabel"; "errorMessage": "errorMessage"; "magnifyingGlassTooltip": "magnifyingGlassTooltip"; "magnifyingGlassEnabledTooltip": "magnifyingGlassEnabledTooltip"; "magnifyingGlassEnabled": "magnifyingGlassEnabled"; "magnifyingGlassDefaultState": "magnifyingGlassDefaultState"; "magnifyingGlassMouseSensibility": "magnifyingGlassMouseSensibility"; "magnifyingSize": "magnifyingSize"; "placeHolderSize": "placeHolderSize"; "signPlaceholderMouseSensibility": "signPlaceholderMouseSensibility"; "enableSignPlaceholder": "enableSignPlaceholder"; "labelSignaturePlaceholder": "labelSignaturePlaceholder"; "automaticallyCopySelection": "automaticallyCopySelection"; "copiedLabel": "copiedLabel"; "automaticallyCopySelectionDelay": "automaticallyCopySelectionDelay"; "automaticallyCopySelectionTooltipCloseDelay": "automaticallyCopySelectionTooltipCloseDelay"; "disablePdfOptions": "disablePdfOptions"; }, { "signPlaceholderCoordinates": "signPlaceholderCoordinates"; "pdfLoaded": "pdfLoaded"; "pdfError": "pdfError"; "magnifyingGlassVisibilityChanged": "magnifyingGlassVisibilityChanged"; }, never, ["[downloadMenu]"], false>;
}
//# sourceMappingURL=pdf-preview.component.d.ts.map