/* 🤖 this file was generated by svg-to-ts*/
export const upIconDragUpDownMedium = {
    name: 'drag_up_down_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="#4E51A7" fill-rule="evenodd" d="M4.862 4.195a.667.667 0 10.943.943L8 2.943l2.195 2.195a.667.667 0 10.943-.943L8.471 1.53a.667.667 0 00-.942 0L4.862 4.195zm6.276 7.61a.667.667 0 00-.943-.943L8 13.057l-2.195-2.195a.667.667 0 10-.943.943l2.667 2.667c.26.26.682.26.942 0l2.667-2.667zM2 8c0-.368.298-.667.667-.667h10.666a.667.667 0 110 1.334H2.667A.667.667 0 012 8z" clip-rule="evenodd"/></svg>`
};
