/* 🤖 this file was generated by svg-to-ts*/
export const upIconPinMedium = {
    name: 'pin_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20"><path fill="currentColor" d="M13.208 10.667L15 12.27v1.25h-4.375v5.02l-.625.626-.625-.625V13.52H5v-1.25l1.667-1.604V3.75H5.625V2.5h8.625v1.25h-1.042v6.917zm-6.52 1.604h6.5l-1.23-1.146V3.75H7.917v7.375l-1.23 1.146z"/></svg>`
};
