import { OnInit, ElementRef, TemplateRef, SimpleChanges, OnChanges, OnDestroy } from '@angular/core';
import { Overlay, OverlayPositionBuilder } from '@angular/cdk/overlay';
import { TooltipConstants, TooltipTrigger } from './tooltip.constants';
import { WindowProperties } from '../../src/lib/providers/window.provider';
import { Platform } from '@angular/cdk/platform';
import { Subject } from 'rxjs';
import { NavigatorProperties } from '../../src/lib/providers/navigator.provider';
import * as i0 from "@angular/core";
export declare class UpTooltipDirective implements OnInit, OnChanges, OnDestroy {
    private overlay;
    private elementRef;
    private overlayPositionBuilder;
    private platform;
    private window;
    private navigator;
    private tooltipConstants;
    content: string | TemplateRef<void>;
    trigger: TooltipTrigger;
    disabledTooltip: boolean;
    persistOnHoverOff: boolean;
    tooltipContextData?: object;
    longPress: number;
    elementClass: string;
    private overlayRef;
    private closeTimer?;
    private tooltipRef;
    touchPressTimeout: any;
    passiveEventListenerOptions: boolean | AddEventListenerOptions;
    destroyListeners: Subject<void>;
    constructor(overlay: Overlay, elementRef: ElementRef, overlayPositionBuilder: OverlayPositionBuilder, platform: Platform, window: WindowProperties, navigator: NavigatorProperties, tooltipConstants: TooltipConstants);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    isIPad(): boolean;
    isMobilePlatform(): boolean;
    get hasHoverTrigger(): boolean;
    get hasClickTrigger(): boolean;
    get isCloseTimerEnabled(): boolean;
    get hasCloseTimer(): boolean;
    setCloseTimer(id: number | undefined): void;
    readonly hide: () => void;
    readonly clearCloseTimer: () => void;
    show(): void;
    touchStart: () => void;
    touchEnd: () => void;
    mouseEnter: () => void;
    mouseOut: () => void;
    click: (event: MouseEvent) => void;
    documentClick(): void;
    private addEventListeners;
    private subscribeToClickEvents;
    private subscribeToMouseEvents;
    private subscribeToTouchEvents;
    private addListener;
    private removeListeners;
    static ɵfac: i0.ɵɵFactoryDeclaration<UpTooltipDirective, never>;
    static ɵdir: i0.ɵɵDirectiveDeclaration<UpTooltipDirective, "[upTooltip]", never, { "content": "upTooltip"; "trigger": "trigger"; "disabledTooltip": "disabledTooltip"; "persistOnHoverOff": "persistOnHoverOff"; "tooltipContextData": "tooltipContextData"; "longPress": "longPress"; }, {}, never, never, false>;
}
//# sourceMappingURL=tooltip.directive.d.ts.map