/* 🤖 this file was generated by svg-to-ts*/
export const upIconColumnsMedium = {
    name: 'columns_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" d="M4 18h4V6H4v12zm6 0h4V6h-4v12zm6 0h4V6h-4v12zM4 20c-.55 0-1.02-.196-1.412-.587A1.927 1.927 0 012 18V6c0-.55.196-1.02.588-1.412A1.923 1.923 0 014 4h16c.55 0 1.021.196 1.413.588.391.391.587.862.587 1.412v12c0 .55-.196 1.021-.587 1.413A1.928 1.928 0 0120 20H4z"/></svg>`
};
