/* 🤖 this file was generated by svg-to-ts*/
export const upIconRejectDocumentMedium = {
    name: 'reject_document_medium',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M5 3.959a2 2 0 012-2h5.586A2 2 0 0114 2.545l4.414 4.414A2 2 0 0119 8.373V19.96a2 2 0 01-2 2H6a1 1 0 01-1-1v-17zm2 16h10V8.373L12.586 3.96H7v16z" clip-rule="evenodd"/><path fill="currentColor" fill-rule="evenodd" d="M9.293 10.293a1 1 0 011.414 0L12 11.586l1.293-1.293a1 1 0 111.414 1.414L13.414 13l1.293 1.293a1 1 0 01-1.414 1.414L12 14.414l-1.293 1.293a1 1 0 01-1.414-1.414L10.586 13l-1.293-1.293a1 1 0 010-1.414z" clip-rule="evenodd"/></svg>`
};
