/* 🤖 this file was generated by svg-to-ts*/
export const upIconFolderSmall = {
    name: 'folder_small',
    data: `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 01.707.293L10.414 6H20a2 2 0 012 2v10a2 2 0 01-2 2H3a1 1 0 001-1v-1h16V8H10a1 1 0 01-.707-.293L7.586 6H4v12H3a1 1 0 00-1 1V6z" clip-rule="evenodd"/><path fill="currentColor" d="M2 19a1 1 0 102 0v-1H3a1 1 0 00-1 1z"/></svg>`
};
